In [2]:
! python -m pip install --upgrade pip
! python -m pip install numpy
! python -m pip install pandas
! python -m pip install matplotlib
! python -m pip install seaborn
! python -m pip install scikit-learn

Requirement already satisfied: pip in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (25.1.1)
Requirement already satisfied: numpy in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (2.2.4)
Requirement already satisfied: pandas in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rick2\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\rick2\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: matplotlib in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (3.10.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.4)
Requirement already satisfied: packaging>=20.0 in c:\users\rick2\appdata\roaming\python\python313\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\rick2\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\rick2\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.2.4)
Requirement already satisfied: pandas>=1.2 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (3.10.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\rick2\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\rick2\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\rick2\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: scikit-learn in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.2.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\rick2\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

In [3]:
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [4]:
import pandas as pd

data = pd.read_csv(r'C:\D_Drive\WorkSpace\ds_and_ml\machine_learning\datasets\titanic\train.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
input_train = data.drop(['PassengerId', 'Survived', 'Name', 'SibSp', 'Parch','Ticket', 'Cabin', 'Embarked'], axis='columns')
target_train = data[['Survived', 'Embarked']]
input_train.head()

   Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [6]:
print(input_train['Age'].skew())

# Calculate mean, median, and mode of 'Age' column
mean_age = input_train['Age'].mean()
median_age = input_train['Age'].median()
mode_age = input_train['Age'].mode()
print(f"Mean Age: {mean_age}, Median Age: {median_age}, Mode Age: {mode_age}, modesize: {mode_age.size}")

# Determine if we should use mean or median to replace NaN values in 'Age'
# If skewness is less than -1 or greater than 1, use median; otherwise

input_train['Age'] = input_train['Age'].fillna(median_age if input_train['Age'].skew() < -1 or input_train['Age'].skew() > 1 else mean_age)
input_train.head()

0.38910778230082704
Mean Age: 29.69911764705882, Median Age: 28.0, Mode Age: 0    24.0
Name: Age, dtype: float64, modesize: 1

   Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [7]:
from sklearn.preprocessing import LabelEncoder

# Prepare input variable
le_train_sex = LabelEncoder()
input_train['Sex_n'] = le_train_sex.fit_transform(input_train['Sex'])
input_train_n = input_train.drop(['Sex'], axis='columns')
input_train_n.head()

   Pclass   Age     Fare  Sex_n
0       3  22.0   7.2500      1
1       1  38.0  71.2833      0
2       3  26.0   7.9250      0
3       1  35.0  53.1000      0
4       3  35.0   8.0500      1

In [8]:
# Prepare target variable
# 'Survived' is the target variable, and 'Embarked' is a categorical feature that needs encoding

le_train_Embarked = LabelEncoder()
target_train['Embarked_n'] = le_train_Embarked.fit_transform(target_train['Embarked'])
target_train_n = target_train.drop(['Embarked'], axis='columns')

target_train_n.head()

C:\Users\rick2\AppData\Local\Temp\ipykernel_37912\519528263.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  target_train['Embarked_n'] = le_train_Embarked.fit_transform(target_train['Embarked'])

   Survived  Embarked_n
0         0           2
1         1           0
2         1           2
3         1           2
4         0           2

In [9]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(input_train_n, target_train_n)

DecisionTreeClassifier()

In [10]:
test_data = pd.read_csv(r'C:\D_Drive\WorkSpace\ds_and_ml\machine_learning\datasets\titanic\test.csv')
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [11]:
input_test = test_data.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis='columns')
input_test['Age'] = input_test['Age'].fillna(input_test['Age'].median() if input_test['Age'].skew() < -1 or input_test['Age'].skew() > 1 else input_test['Age'].mean())
input_test['Fare'] = input_test['Fare'].fillna(input_test['Fare'].median() if input_test['Age'].skew() < -1 or input_test['Age'].skew() > 1 else input_test['Fare'].mean())   
input_test.head()

   Pclass     Sex   Age     Fare
0       3    male  34.5   7.8292
1       3  female  47.0   7.0000
2       2    male  62.0   9.6875
3       3    male  27.0   8.6625
4       3  female  22.0  12.2875

In [12]:
le_test_sex = LabelEncoder()
input_test['Sex_n'] = le_test_sex.fit_transform(input_test['Sex'])
input_test_n = input_test.drop(['Sex'], axis='columns')
input_test_n.head()

   Pclass   Age     Fare  Sex_n
0       3  34.5   7.8292      1
1       3  47.0   7.0000      0
2       2  62.0   9.6875      1
3       3  27.0   8.6625      1
4       3  22.0  12.2875      0

In [13]:
model.predict(input_test_n)

array([[1, 2],
       [0, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 0],
       [0, 2],
       [1, 0],
       [1, 2],
       [0, 2],
       [1, 0],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 2],
       [1, 2],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 2],
       [0, 2],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 2],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 1],
       [1, 0],
       [1, 2],
       [1, 0],
       [0, 0],
       [1, 2],
       [1, 2],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 2],
       [1, 0],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 1],
       [1, 2],
       [1, 2],
       [1, 1],
       [0, 2],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 2],
       [1, 2],
       [0, 0],
       [1, 2],
       [0, 2],
       [0, 2],
       [1, 2],
       [0, 2],
       [1, 1],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 0],
       [1, 1],
       [1, 2],
       [0, 1],
       [1, 2],
       [0, 2],
       [0, 2],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 0],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [0, 2],
       [0, 1],
       [0, 2],
       [1, 1],
       [0, 2],
       [0, 2],
       [0, 1],
       [0, 0],
       [0, 2],
       [0, 2],
       [0, 1],
       [1, 0],
       [1, 2],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 2],
       [1, 2],
       [1, 2],
       [0, 1],
       [1, 0],
       [0, 2],
       [0, 1],
       [1, 2],
       [0, 2],
       [1, 1],
       [0, 2],
       [0, 2],
       [1, 2],
       [0, 0],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 0],
       [0, 2],
       [0, 2],
       [1, 2],
       [0, 2],
       [0, 2],
       [1, 0],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 1],
       [1, 2],
       [1, 0],
       [1, 2],
       [0, 2],
       [1, 2],
       [0, 2],
       [0, 2],
       [1, 0],
       [0, 2],
       [0, 2],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 2],
       [1, 2],
       [1, 2],
       [0, 2],
       [1, 2],
       [1, 0],
       [0, 2],
       [0, 2],
       [1, 2],
       [0, 1],
       [1, 0],
       [0, 2],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 1],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 0],
       [0, 2],
       [1, 1],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 1],
       [1, 2],
       [1, 2],
       [0, 2],
       [1, 2],
       [0, 2],
       [1, 2],
       [1, 2],
       [0, 0],
       [0, 0],
       [0, 2],
       [0, 1],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 0],
       [1, 2],
       [1, 0],
       [0, 0],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 0],
       [0, 2],
       [1, 2],
       [0, 2],
       [1, 2],
       [0, 0],
       [1, 2],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 1],
       [0, 2],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 2],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 0],
       [0, 1],
       [1, 2],
       [1, 1],
       [0, 0],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 2],
       [0, 1],
       [0, 0],
       [1, 0],
       [0, 2],
       [0, 2],
       [0, 0],
       [0, 0],
       [0, 2],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 0],
       [0, 0],
       [0, 2],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 2],
       [0, 1],
       [1, 2],
       [0, 2],
       [1, 2],
       [0, 0],
       [0, 2],
       [0, 2],
       [1, 0],
       [0, 2],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 0],
       [0, 2],
       [1, 2],
       [1, 2],
       [0, 2],
       [1, 2],
       [0, 0],
       [0, 2],
       [0, 2],
       [1, 2],
       [0, 0],
       [0, 0],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 0],
       [0, 2],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 2],
       [1, 0],
       [0, 2],
       [0, 2],
       [0, 2],
       [1, 0],
       [0, 2],
       [1, 2],
       [0, 2],
       [0, 1],
       [1, 1],
       [0, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [0, 2],
       [0, 0],
       [0, 2],
       [1, 0],
       [1, 0],
       [0, 2],
       [1, 2],
       [0, 2],
       [0, 2],
       [1, 0],
       [1, 0],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 2],
       [0, 1],
       [0, 2],
       [0, 0],
       [1, 2],
       [0, 2],
       [1, 2],
       [0, 2],
       [0, 2],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 0],
       [0, 2],
       [0, 2],
       [0, 0],
       [1, 2],
       [0, 2],
       [1, 0],
       [0, 2],
       [0, 1],
       [1, 2],
       [0, 2],
       [1, 2],
       [0, 2],
       [0, 2],
       [1, 0],
       [0, 2],
       [1, 2],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 2],
       [1, 1],
       [0, 2],
       [1, 0],
       [0, 2],
       [0, 2],
       [0, 0]])